Added ssh collector
movidius/windows_exporter pull request #3
Opened 2022-01-26 07:56 UTC by wdlaszlo

TODO: Add documentation

2022-01-26 13:23 UTC, wdlaszlo commented
> EISW-28504

Added.

2022-01-27 07:01 UTC, rkiss requested changes

2022-01-27 07:01 UTC, rkiss commented on docs/collector.ssh.md
> +The path to OpenSSH EVTX file. When not used, the following value is used: `C:\\Windows\\System32\\Winevt\\Logs\\OpenSSH%4Operational.evtx`.
use windir

2022-01-28 08:12 UTC, wdlaszlo commented on docs/collector.ssh.md
> +The path to OpenSSH EVTX file. When not used, the following value is used: `C:\\Windows\\System32\\Winevt\\Logs\\OpenSSH%4Operational.evtx`.
Outdated. This was changed to log name.

2022-01-28 08:13 UTC, wdlaszlo commented on collector/ssh.go
> +	for e := range ef.Events() {
Done using a goroutine, and a channel.

2022-01-28 08:14 UTC, wdlaszlo commented on collector/ssh.go
> +	).Default("C:\\Windows\\System32\\Winevt\\Logs\\OpenSSH%4Operational.evtx").String()
Outdated. This was changed to OpenSSH log name.

2022-01-28 10:02 UTC, rkiss requested changes

2022-01-28 11:16 UTC, wdlaszlo commented on collector/ssh.go
> +	for e := range ep.FetchEvents([]string{channel}, wevtapi.EvtSubscribeStartAtOldestRecord) {
I assumed that we need the events that had occurred before node exporter started. Since this function is called only once in a goroutine, It will get all the events only once, starting from the oldest and then if new events are found, they will be pushed to the channel and then it will process only those events that were not previously processed. I tested `EvtSubscribeStartAtOldestRecord` and it gave me exactly what I needed for this. 

> For example, let's assume that there are 2 SSH active connections made before starting the Node Exporter. With the current code, we will count those as well and the real number of connections will be valid. 

I also investigated `EvtSubscribeToFutureEvents`. Basically, this will get us only the events that had occurred after the Node Exporter started.

> In this case, using the same example as above, we won't count the number those 2 connections.

2022-01-28 11:17 UTC, wdlaszlo commented on collector/ssh.go
> +func processEvent(c *SSHConnectionsCollector, log string) {
There is no reason. I moved the code.

2022-01-28 11:18 UTC, wdlaszlo commented on collector/ssh.go
> +func processEvents(c *SSHConnectionsCollector) {
There is no reason. I moved the code into `collect` function.

2022-01-28 11:20 UTC, wdlaszlo commented on collector/ssh.go
> +func monitorEvents(channel string) {
Corrected.

2022-01-28 11:20 UTC, wdlaszlo commented on collector/ssh.go
> +		// j := e.ToJSONEvent()
Removed. I don't think that we need to log this information.

2022-01-28 11:20 UTC, wdlaszlo commented on collector/ssh.go
> +		// j := e.ToJSONEvent()
Removed. I don't think that we need to log this information.

2022-01-28 11:40 UTC, wdlaszlo commented on collector/ssh.go
> +func isLoginEvent(log string) (matches []string) {
Correct, refactoring done.

2022-01-31 14:31 UTC, rkiss approved these changes

2022-01-31 14:31 UTC, merged